FROM python:3.10-slim

# Set up working directory
WORKDIR /tmp

# Install Dagster dependencies
RUN pip install \
    dagster \
    dagster-graphql \
    dagster-webserver \
    dagster-postgres \
    dagster-docker  \
    pandas  \
    psycopg2-binary  \
    pyarrow  \
    boto3  \
    dagster-pandas  \
    dagit  \
    dbt-postgres  \
    dbt-core  \
    minio  


# Move to application directory
WORKDIR /opt/dagster/app

# Copy repo file into image (relative to build context)
COPY fix_sensor.py /opt/dagster/app

# Expose gRPC port
EXPOSE 4000

# Start the Dagster gRPC server
CMD ["dagster", "api", "grpc", "-h", "0.0.0.0", "-p", "4000", "-f", "fix_sensor.py"]
