FROM python:3.10-slim

# Set up working directory
WORKDIR /tmp

# Install Dagster dependencies
RUN pip install \
    dagster \
    dagster-dbt \
    dagster-graphql \
    dagster-webserver \
    dagster-postgres \
    dagster-docker  \
    pandas  \
    psycopg2-binary  \
    pyarrow  \
    boto3  \
    dagster-pandas  \
    dagit  \
    dbt-postgres  \
    dbt-duckdb  \
    dbt-core  \
    minio  


# Move to application directory
WORKDIR /opt/dagster/app

# Copy repo file into image (relative to build context)
COPY . /opt/dagster/app

COPY /pictet_fix_project/.dbt/profiles.yml /opt/dagster/app/pictet_fix_project/.dbt/profiles.yml


# Expose gRPC port
EXPOSE 4000

# Start the Dagster gRPC server
# ...autres instructions...
ENV DBT_TARGET=container

CMD ["dagster", "api", "grpc", "-h", "0.0.0.0", "-p", "4000", "-f", "definition.py"]
