# Dagster libraries to run both dagster-webserver and the dagster-daemon. Does not
# need to have access to any pipeline code.

FROM python:3.10-slim

# Install Dagster dependencies with compatible versions
RUN pip install \
    dagster==1.11.0 \
    dagster-graphql==1.11.0 \
    dagster-webserver==1.11.0 \
    dagster-postgres==0.27.0 \
    dagster-docker==0.27.0

# Set $DAGSTER_HOME and copy Dagster instance and workspace YAML there
ENV DAGSTER_HOME=/opt/dagster/dagster_home/

RUN mkdir -p $DAGSTER_HOME

COPY dagster.yaml workspace.yaml $DAGSTER_HOME

WORKDIR $DAGSTER_HOME