pictet_fix_project:
  target: dev
  outputs:
    # Local development profile
    dev:
      type: duckdb
      path: /Users/larcher/FIX_trading/duck_db/duckdb_pictet  # Local path to DuckDB file
      threads: 4
      extensions:
        - httpfs
        - parquet
      settings:
        s3_region: us-east-1
        s3_url_style: path
        s3_endpoint: localhost:9000  # Local MinIO endpoint
        s3_access_key_id: minioadmin
        s3_secret_access_key: minioadmin
        s3_use_ssl: false

    # Containerized deployment profile
    container:
      type: duckdb
      path: /opt/dagster/duck_db/duckdb_pictet  # Path inside the container
      threads: 4
      extensions:
        - httpfs
        - parquet
      settings:
        s3_region: us-east-1
        s3_url_style: path
        s3_endpoint: minio:9000  # MinIO container hostname
        s3_access_key_id: minioadmin
        s3_secret_access_key: minioadmin
        s3_use_ssl: false