{{
  config(
    materialized='table',
    schema='03_analytics',
    alias='dim_fix_message_types'
  )
}}

SELECT '0' AS msg_type, 'Heartbeat' AS msg_type_description
UNION ALL SELECT '1', 'Test Request'
UNION ALL SELECT '2', 'Resend Request'
UNION ALL SELECT '3', 'Reject'
UNION ALL SELECT '4', 'Sequence Reset'
UNION ALL SELECT '5', 'Logout'
UNION ALL SELECT '6', 'Indication of Interest'
UNION ALL SELECT '7', 'Advertisement'
UNION ALL SELECT '8', 'Execution Report'
UNION ALL SELECT '9', 'Order Cancel Reject'
UNION ALL SELECT 'A', 'Logon'
UNION ALL SELECT 'D', 'New Order Single'
UNION ALL SELECT 'E', 'New Order List'
UNION ALL SELECT 'F', 'Order Cancel Request'
UNION ALL SELECT 'G', 'Order Replacement Request'
UNION ALL SELECT 'H', 'Order Status Request'
UNION ALL SELECT 'J', 'Allocation'
UNION ALL SELECT 'K', 'List Cancel Request'
UNION ALL SELECT 'L', 'List Execute'
UNION ALL SELECT 'M', 'List Status Request'
UNION ALL SELECT 'N', 'List Status'
UNION ALL SELECT 'P', 'Allocation ACK'
UNION ALL SELECT 'Q', 'Don t Know Trade (DK)'
UNION ALL SELECT 'R', 'Quote Request'
UNION ALL SELECT 'S', 'Quote'
UNION ALL SELECT 'T', 'Settlement Instructions'
UNION ALL SELECT 'V', 'Market Data Request'
UNION ALL SELECT 'W', 'Market Data Snapshot/Full Refresh'
UNION ALL SELECT 'X', 'Market Data Incremental Refresh'
UNION ALL SELECT 'Y', 'Market Data Request Reject'
UNION ALL SELECT 'Z', 'Quote Cancel'
UNION ALL SELECT 'a', 'Quote Status Request'
UNION ALL SELECT 'b', 'Mass Quote Acknowledgement'
UNION ALL SELECT 'c', 'Security Definition Request'
UNION ALL SELECT 'd', 'Security Definition'
UNION ALL SELECT 'e', 'Security Status Request'
UNION ALL SELECT 'f', 'Security Status'
UNION ALL SELECT 'g', 'Trading Session Status Request'
UNION ALL SELECT 'h', 'Trading Session Status'
UNION ALL SELECT 'j', 'Mass Quote'
UNION ALL SELECT 'k', 'Business Message Reject'
UNION ALL SELECT 'l', 'Bid Request'
UNION ALL SELECT 'm', 'Bid Response'
UNION ALL SELECT 'n', 'New Order Multileg'
UNION ALL SELECT 'o', 'Multileg Order Cancel/Replace'
UNION ALL SELECT 'p', 'Trade Capture Report Request'
UNION ALL SELECT 'q', 'Trade Capture Report'
UNION ALL SELECT 'r', 'Order Mass Status Request'
UNION ALL SELECT 's', 'Quote Request Reject'
UNION ALL SELECT 't', 'RFQ Request'
UNION ALL SELECT 'u', 'Quote Status Report'
UNION ALL SELECT 'v', 'Quote Response'
UNION ALL SELECT 'w', 'Confirmation'
UNION ALL SELECT 'x', 'Confirmation Ack'
UNION ALL SELECT 'y', 'Confirmation Request'
UNION ALL SELECT 'z', 'Settlement Instruction Request'
UNION ALL SELECT 'AA', 'Assignment Report'
UNION ALL SELECT 'AB', 'Collateral Request'
UNION ALL SELECT 'AC', 'Collateral Assignment'
UNION ALL SELECT 'AD', 'Collateral Response'
UNION ALL SELECT 'AE', 'News'
UNION ALL SELECT 'AF', 'Collateral Report'
UNION ALL SELECT 'AG', 'Collateral Inquiry'
UNION ALL SELECT 'AH', 'Collateral Inquiry Ack'
UNION ALL SELECT 'AI', 'Network Counterparty System Status Request'
UNION ALL SELECT 'AJ', 'Network Counterparty System Status Response'
UNION ALL SELECT 'AK', 'User Request'
UNION ALL SELECT 'AL', 'User Response'
UNION ALL SELECT 'AM', 'Collateral Account Report'
UNION ALL SELECT 'AN', 'Party Risk Limits Request'
UNION ALL SELECT 'AO', 'Party Risk Limits Report'
UNION ALL SELECT 'AP', 'Party Risk Limits Report ACK'
UNION ALL SELECT 'AQ', 'Risk Limit Update Report'
UNION ALL SELECT 'AR', 'Request For Positions'
UNION ALL SELECT 'AS', 'Request For Positions Ack'
UNION ALL SELECT 'AT', 'Position Report'
UNION ALL SELECT 'AU', 'Request For Positions Confirm'
UNION ALL SELECT 'AV', 'Trade Capture Report Ack'
UNION ALL SELECT 'AW', 'Trade Capture Report Rejection'
UNION ALL SELECT 'AX', 'Trade Capture Report Status Request'
UNION ALL SELECT 'AY', 'Trade Capture Report Status'
UNION ALL SELECT 'AZ', 'Security List Request'
UNION ALL SELECT 'BA', 'Security List'
UNION ALL SELECT 'BB', 'Security List Update Report'
UNION ALL SELECT 'BC', 'Security Definition Update Report'
UNION ALL SELECT 'BD', 'Adjusted Order Mass Status Request'
UNION ALL SELECT 'BE', 'Adjusted Order Mass Status Report'
UNION ALL SELECT 'BF', 'Adjusted Quote Report'
UNION ALL SELECT 'BG', 'Order Mass Action Report'
UNION ALL SELECT 'BH', 'Order Mass Action Request'
UNION ALL SELECT 'BI', 'Order Mass Action Request ACK'
UNION ALL SELECT 'BJ', 'Trade Capture Report Cancel'
UNION ALL SELECT 'BK', 'Trade Capture Report Amend'
UNION ALL SELECT 'BL', 'Trade Capture Report Replace'
UNION ALL SELECT 'BM', 'Trade Capture Report Rejection Ack'
UNION ALL SELECT 'BN', 'Trade Capture Report Rejection Reject'
UNION ALL SELECT 'BO', 'Trade Capture Report Rejection Status Request'
UNION ALL SELECT 'BP', 'Trade Capture Report Rejection Status'
UNION ALL SELECT 'BQ', 'Trade Capture Report Query'
UNION ALL SELECT 'BR', 'Trade Capture Report Query ACK'
UNION ALL SELECT 'BS', 'Trade Capture Report Query Reject'
UNION ALL SELECT 'BT', 'Trade Capture Report Query Status Request'
UNION ALL SELECT 'BU', 'Trade Capture Report Query Status'
UNION ALL SELECT 'BV', 'Trade Capture Report Query Status Report'
UNION ALL SELECT 'BW', 'Trade Capture Report Query Rejection'
UNION ALL SELECT 'BX', 'Trade Capture Report Query Rejection Ack'
UNION ALL SELECT 'BY', 'Trade Capture Report Query Rejection Status Request'
UNION ALL SELECT 'BZ', 'Trade Capture Report Query Rejection Status'
UNION ALL SELECT 'CA', 'Trade Capture Report Query Rejection Status Report'
UNION ALL SELECT 'CB', 'Trade Capture Report Query Rejection Reject'
UNION ALL SELECT 'CC', 'Trade Capture Report Query Rejection Confirm'
UNION ALL SELECT 'CD', 'Trade Capture Report Query Rejection Status Confirm'
UNION ALL SELECT 'CE', 'Trade Capture Report Query Rejection Status Reject'
UNION ALL SELECT 'CF', 'Trade Capture Report Query Rejection Status Confirm Ack'
UNION ALL SELECT 'CG', 'Trade Capture Report Query Rejection Status Confirm Reject'
UNION ALL SELECT 'CH', 'Trade Capture Report Query Rejection Status Confirm Status Request'
UNION ALL SELECT 'CI', 'Trade Capture Report Query Rejection Status Confirm Status'
UNION ALL SELECT 'CJ', 'Trade Capture Report Query Rejection Status Confirm Status Report'
UNION ALL SELECT 'CK', 'Trade Capture Report Query Rejection Status Confirm Status Rejection'
UNION ALL SELECT 'CL', 'Trade Capture Report Query Rejection Status Confirm Status Rejection Ack'
UNION ALL SELECT 'CM', 'Trade Capture Report Query Rejection Status Confirm Status Rejection Status Request'
UNION ALL SELECT 'CN', 'Trade Capture Report Query Rejection Status Confirm Status Rejection Status'
UNION ALL SELECT 'CO', 'Trade Capture Report Query Rejection Status Confirm Status Rejection Status Report'
UNION ALL SELECT 'CP', 'Trade Capture Report Query Rejection Status Confirm Status Rejection Status Rejection'